config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :contacts
    root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    before_action :find_contact, only: [:show, :edit, :update, :destroy]
    def index
        @contacts = Contact.all.order("created_at DESC")  
    end

    def show 
       
    end

    def new
        @contact = Contact.new  
    end

    def create   
        @contact = Contact.new(contact_params)
            if @contact.save
                redirect_to root_path
            else
                render 'new'
            end
    end

    def edit
       
    end

    def update
        if @contact.update(contact_params)
          flash[:success] = "Contact was successfully updated"
          redirect_to contact_path(@contact)
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def destroy
        
        if @contact.destroy
            flash[:success] = 'Contact was successfully deleted.'
            redirect_to root_path
        else
            flash[:error] = 'Something went wrong'
            redirect_to objects_url
        end
    end
    
    
    

    private 
        def contact_params
             params.require(:contact).permit(:name, :email, :cell, :date)
        end

        def find_contact
            @contact = Contact.find(params[:id])
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
    <%= f.input :name, label: "Name" %>
    <%= f.input :email, placeholder: 'user@domain.com' %>
    <%= f.input :cell, as: :integer %>
    <%= f.input :date, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year %>
    <%= f.button :submit, class: "btn btn-info" %>

<% end %>

app/views/contacts/edit.html.erb
<br>
<hr>
<h1>Edit the Contact</h1>
<hr>
    <%= render 'form' %>
    <br>
    <%= link_to "Go Home", root_path, class: "btn btn-dark" %>

app/views/contacts/index.html.erb
<br>
<hr>
    <div class="row">
        <div class="col-10">
            <h2>Contacts</h2>
        </div>
        <div class="col-2">
            <%= link_to "Create", new_contact_path , class: "btn btn-warning" %>
        </div>
    </div>
    
    <hr>
    <div class="row">
        <div class="col-12" style="">
            <div class="panel panel-default list-group-panel">
                <div class="panel-body">
                    <ul class="list-group list-group-header bg-primary">
                        <li class="list-group-item list-group-body bg-primary" style="color:white">
                            <div class="row">
                                <div class="col-1 text-left">#No:</div>
                                <div class="col-2 text-left">Name</div>
                                <div class="col-2">Email</div>
                                <div class="col-2">Cell</div>
                                <div class="col-2">Date of Birth</div>
                            </div>
                        </li>
                    </ul>
<% @contacts.each do |contact| %>                    
                    <ul class="list-group list-group-body" style="">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-1 text-left"><%= contact.id %></div>
                                <div class="col-2 text-left" style=""> <%= contact.name %> </div>
                                <div class="col-2" style=""><%= contact.email %></div>
                                <div class="col-2" style=""><%= contact.cell %></div>
                                <div class="col-2" style=""><%= contact.date %></div>
                                <div class="col-2" style=""><%= link_to "Edit", edit_contact_path(contact.id), class: "btn btn-success" %></div>
                                <%= link_to "Profile", contact_path(contact.id), class: "btn btn-secondary" %>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/contacts/new.html.erb
<hr>
<h1>Create new Contact</h1>
<hr>
    <%= render 'form' %>
    <br>
    <%= link_to "Go Home", root_path, class: "btn btn-secondary" %>

app/views/contacts/show.html.erb
<hr>
<br>
<h2>Single Contact</h2>
<hr>
<div class="col-12" >
        <div class="panel panel-info ">
          <div class="panel-heading ">
            <h3 class="panel-title">ID: <%= @contact.id %></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
              <div class=" col-md-9 "> 
                <table class="table table-user-information">
                  <tbody>
                      <tr>
                          <td>Name:</td>
                          <td><%= @contact.name %></td>
                        </tr>
                    <tr>
                      <td>Email:</td>
                      <td><a href=""><%= @contact.email %></a></td>
                    </tr>
                    <tr>
                      <td>Phone Number:</td>
                      <td><%= @contact.cell %>- (Mobile)</td>
                    </tr>
                    <tr>
                      <td>Date of Birth</td>
                      <td><%= @contact.date %></td>
                    </tr>              
                  </tbody>
                </table>
            
            <%= link_to "Update", edit_contact_path(@contact), class: "btn btn-primary" %>
            <%= link_to "Delete", contact_path(@contact), method: :delete, data: {confirm: "Are you sure?"} ,class: "btn btn-danger" %>
            
              </div>            

            </div>

          </div>
               <div class="panel-footer default">
                    
                    <%= link_to "Go Home", root_path, class: "btn btn-dark" %>
                  </div>
          
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddressBook</title>
    <%= csrf_meta_tags %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
  
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>